### ISSUE TITLE
Build a node.js web server that prints Hello World to the browser

### ISSUE THREAD

**Issue by kennymeyers** [dotsara/100-projects#2]

**Comment by dotsara** [comment]
Leaving a breadcrumb trail for how I'm going about this…
- [An Absolute Beginner's Guide to Node.js](http://blog.modulus.io/absolute-beginners-guide-to-nodejs)
-  [Build Your First HTTP server in Node.js](http://blog.modulus.io/build-your-first-http-server-in-nodejs)
-  [Node Hero: Getting Started with Node.js Tutorial](https://blog.risingstack.com/node-hero-tutorial-getting-started-with-node-js/)
- [Installing NVM](https://github.com/creationix/nvm)

(links 2 & 3 also recommended by @stickel)

**Comment by dotsara** [comment]
Also: https://nodejs.org/api/synopsis.html

**Comment by dotsara** [comment]
[Anatomy of an HTTP transaction](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/)

**Comment by dotsara** [comment]
@kennymeyers check it! Getting started (:  https://github.com/dotsara/my-first-node-js-server/commit/18acfcd2d1d689b6ccd449e61da06341f82329c2

**Comment by kennymeyers** [comment]
Yay! Nicely done!
