### ISSUE TITLE
Basketball hoop!

### ISSUE THREAD

**Issue by kennymeyers** [dotsara/100-projects#4]
Make a touch-based game for dragging basketballs into a hoop using touch

**Comment by dotsara** [comment]
Got started on this and got it working on my laptop and… _then_ realized I was using `drag` events and not `touch` events. Ha, but 😐 . So, now reading more about touch events. I don't expect to get back to this until Tuesday.

Collecting these in one place in case I reboot…
- http://www.html5rocks.com/en/mobile/touch/#toc-events
- http://www.html5rocks.com/en/mobile/mobifying/
- http://touchpunch.furf.com/
- http://tutorials.jenkov.com/responsive-mobile-friendly-web-design/touch-events-in-javascript.html
- http://callmenick.com/post/touch-events-instead-of-click-or-hover-with-javascript
